### ISSUE TITLE
infersent.py: invalid device ordinal at torch/csrc/cuda/Module.cpp:84

### ISSUE THREAD

**Issue by loretoparisi** [facebookresearch/SentEval#3]
I get this error running `infersent.py`
```
python infersent.py
/root/miniconda2/lib/python2.7/site-packages/torch/serialization.py:284: SourceChangeWarning: source code of class 'models.BLSTMEncoder' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
THCudaCheck FAIL file=torch/csrc/cuda/Module.cpp line=84 error=10 : invalid device ordinal
Traceback (most recent call last):
  File "infersent.py", line 56, in <module>
    params_senteval.infersent = torch.load(MODEL_PATH)
  File "/root/miniconda2/lib/python2.7/site-packages/torch/serialization.py", line 229, in load
    return _load(f, map_location, pickle_module)
  File "/root/miniconda2/lib/python2.7/site-packages/torch/serialization.py", line 377, in _load
    result = unpickler.load()
  File "/root/miniconda2/lib/python2.7/site-packages/torch/serialization.py", line 348, in persistent_load
    data_type(size), location)
  File "/root/miniconda2/lib/python2.7/site-packages/torch/serialization.py", line 85, in default_restore_location
    result = fn(storage, location)
  File "/root/miniconda2/lib/python2.7/site-packages/torch/serialization.py", line 67, in _cuda_deserialize
    return obj.cuda(device_id)
  File "/root/miniconda2/lib/python2.7/site-packages/torch/_utils.py", line 57, in _cuda
    with torch.cuda.device(device):
  File "/root/miniconda2/lib/python2.7/site-packages/torch/cuda/__init__.py", line 127, in __enter__
    torch._C._cuda_setDevice(self.idx)
RuntimeError: cuda runtime error (10) : invalid device ordinal at torch/csrc/cuda/Module.cpp:84
```

*NOTE*. The `bow.py` works, and all tasks are evaluated correctly.

**Comment by aconneau** [comment]
Can you remove this and re-run : https://github.com/facebookresearch/SentEval/blob/master/examples/infersent.py#L26 ( the torch.cuda.set_device(0) ) and tell me if that fixes the problem?
Thanks!

**Comment by aconneau** [comment]
43742948f1d08dd26b8f475958adf16a8ebbee4b will remove the "SourceChangeWarning" message.

**Comment by loretoparisi** [comment]
@aconneau Ok I will try i out!

**Comment by loretoparisi** [comment]
@aconneau removed, it seems the error stays on. I have a nvidia gpu here:

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 367.57                 Driver Version: 367.57                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GRID K520           Off  | 0000:00:03.0     Off |                  N/A |
| N/A   37C    P8    17W / 125W |      0MiB /  4036MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by loretoparisi** [comment]
@aconneau I think that `torch.cuda.set_device(0)` it's ok, but the `params_senteval.infersent = torch.load(MODEL_PATH)` could be the issue.

I have replaced with

```
params_senteval.infersent = torch.load(MODEL_PATH, map_location=lambda storage, loc: storage)
```

as described [here](https://discuss.pytorch.org/t/resolved-cuda-runtime-error/1729).

Now I get

```
2017-07-06 12:55:29,866 : ***** Transfer task : MR *****


Found 18594(/20306) words with glove vectors
Vocab size : 18594
2017-07-06 12:55:35,890 : Generating sentence embeddings
Traceback (most recent call last):
  File "infersent.py", line 61, in <module>
    results_transfer = se.eval(transfer_tasks)
  File "../senteval.py", line 51, in eval
    self.results = {x:self.eval(x) for x in name}
  File "../senteval.py", line 51, in <dictcomp>
    self.results = {x:self.eval(x) for x in name}
  File "../senteval.py", line 85, in eval
    self.results = self.evaluation.run(self.batcher, self.params)
  File "../binary.py", line 44, in run
    embeddings = batcher(batch, params)
  File "infersent.py", line 35, in batcher
    embeddings = params.infersent.encode(sentences, bsize=params.batch_size, tokenize=False)
  File "/mxmlib/SentEval/examples/models.py", line 179, in encode
    batch = self.forward((batch, lengths[stidx:stidx + bsize])).data.cpu().numpy()
  File "/mxmlib/SentEval/examples/models.py", line 46, in forward
    sent_output = self.enc_lstm(sent_packed)[0] #seqlen x batch x 2*nhid
  File "/root/miniconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/miniconda2/lib/python2.7/site-packages/torch/nn/modules/rnn.py", line 91, in forward
    output, hidden = func(input, self.all_weights, hx)
  File "/root/miniconda2/lib/python2.7/site-packages/torch/nn/_functions/rnn.py", line 343, in forward
    return func(input, *fargs, **fkwargs)
  File "/root/miniconda2/lib/python2.7/site-packages/torch/autograd/function.py", line 202, in _do_forward
    flat_output = super(NestedIOFunction, self)._do_forward(*flat_input)
  File "/root/miniconda2/lib/python2.7/site-packages/torch/autograd/function.py", line 224, in forward
    result = self.forward_extended(*nested_tensors)
  File "/root/miniconda2/lib/python2.7/site-packages/torch/nn/_functions/rnn.py", line 285, in forward_extended
    cudnn.rnn.forward(self, input, hx, weight, output, hy)
  File "/root/miniconda2/lib/python2.7/site-packages/torch/backends/cudnn/rnn.py", line 255, in forward
    _copyParams(weight, params)
  File "/root/miniconda2/lib/python2.7/site-packages/torch/backends/cudnn/rnn.py", line 183, in _copyParams
    assert param_from.type() == param_to.type()
AssertionError
```

**Comment by aconneau** [comment]
1) Ok so what happened is that the gpu device id is saved with the model when you do "torch.save(..)". And during my experiments the device id of infersent.allnli.pickle was 2, and the one of infersent.snli.pickle was 1, while it should be 0 (otherwise if you don't 3 gpus you can't load it). My mistake, thanks for noticing this! **I just modified the file on amazon web service so that the device id for the models is now 0**.
Could you download the .pickle again and let me know if you have the same mistake?

2) For the CPU part, while I would discourage encoding sentences using the CPU (since it's a BiLSTM with a large hidden size : 2048), just add "params.infersent.use_cuda=False" right after loading the network and it should work (though it is going to be slow as mentionned here : https://github.com/facebookresearch/InferSent/blob/master/encoder/play.ipynb).

**Comment by loretoparisi** [comment]
@aconneau ok! Just to be clear:

```
root@79714f86149f:/mxmlib/SentEval# curl -Lo examples/infersent.allnli.pickle https://s3.amazonaws.com/senteval/infersent/infersent.allnli.pickle
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  147M  100  147M    0     0  46.3M      0  0:00:03  0:00:03 --:--:-- 46.3M
root@79714f86149f:/mxmlib/SentEval# curl -Lo examples/infersent.snli.pickle https://s3.amazonaws.com/senteval/infersent/infersent.snli.pickle
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  147M  100  147M    0     0  56.8M      0  0:00:02  0:00:02 --:--:-- 56.8M
```

these ones right?

**Comment by aconneau** [comment]
Yes, they should have been updated.

**Comment by loretoparisi** [comment]
trying again...

```
root@79714f86149f:/mxmlib/SentEval# curl -Lo examples/infersent.snli.pickle https://s3.amazonaws.com/senteval/infersent/infersent.snli.pickle
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  147M  100  147M    0     0  57.0M      0  0:00:02  0:00:02 --:--:-- 57.0M
root@79714f86149f:/mxmlib/SentEval# curl -Lo examples/infersent.allnli.pickle https://s3.amazonaws.com/senteval/infersent/infersent.allnli.pickle
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  147M  100  147M    0     0  43.1M      0  0:00:03  0:00:03 --:--:-- 43.1M
root@79714f86149f:/mxmlib/SentEval# cd examples/
root@79714f86149f:/mxmlib/SentEval/examples# python infersent.py 
THCudaCheck FAIL file=torch/csrc/cuda/Module.cpp line=84 error=10 : invalid device ordinal
Traceback (most recent call last):
  File "infersent.py", line 56, in <module>
    params_senteval.infersent = torch.load(MODEL_PATH)
  File "/root/miniconda2/lib/python2.7/site-packages/torch/serialization.py", line 229, in load
    return _load(f, map_location, pickle_module)
  File "/root/miniconda2/lib/python2.7/site-packages/torch/serialization.py", line 377, in _load
    result = unpickler.load()
  File "/root/miniconda2/lib/python2.7/site-packages/torch/serialization.py", line 348, in persistent_load
    data_type(size), location)
  File "/root/miniconda2/lib/python2.7/site-packages/torch/serialization.py", line 85, in default_restore_location
    result = fn(storage, location)
  File "/root/miniconda2/lib/python2.7/site-packages/torch/serialization.py", line 67, in _cuda_deserialize
    return obj.cuda(device_id)
  File "/root/miniconda2/lib/python2.7/site-packages/torch/_utils.py", line 57, in _cuda
    with torch.cuda.device(device):
  File "/root/miniconda2/lib/python2.7/site-packages/torch/cuda/__init__.py", line 127, in __enter__
    torch._C._cuda_setDevice(self.idx)
RuntimeError: cuda runtime error (10) : invalid device ordinal at torch/csrc/cuda/Module.cpp:84
```

How to be sure if the files are up-to-date? Maybe S3 is caching...

**Comment by aconneau** [comment]
Could you run this:
`
for p in infersent.enc_lstm.parameters():
    print p.get_device()
`
and tell me what you get?

**Comment by loretoparisi** [comment]
uhm! I get a `AttributeError: 'module' object has no attribute 'enc_lstm'`...

**Comment by soumith** [comment]
here's a simple fix for you (alexis is fixing the checkpoints soon):

```
params_senteval.infersent = torch.load(MODEL_PATH, map_location={'cuda:1' : 'cuda:0', 'cuda:2' : 'cuda:0'})
```

**Comment by loretoparisi** [comment]
@soumith thank you it's starting...

```
2017-07-06 14:34:52,159 : ***** Transfer task : MR *****


Found 18594(/20306) words with glove vectors
Vocab size : 18594
2017-07-06 14:34:58,159 : Generating sentence embeddings
2017-07-06 14:35:24,026 : Generated sentence embeddings
2017-07-06 14:35:24,027 : Training pytorch-LogReg with (inner) 10-fold cross-validation
...
```

Let's wait the results!

**Comment by aconneau** [comment]
The checkpoints that can be downloaded from the links have been modified.
With these news checkpoints, it should work directly when using "torch.load".

**Comment by loretoparisi** [comment]
@aconneau ok thanks. I will try then without the hotfixt above :)

**Comment by alexbhandari** [comment]
I just got this issue using the checkpoint from
https://s3.amazonaws.com/senteval/infersent/infersent.allnli.pickle

remapping the cuda device ID fixed it for me, but it looks like the checkpoints may have been updated with a GPU device ID > 0 again.

**Comment by aconneau** [comment]
@alexbhandari Thanks for pointing this out. It is now fixed.
